# Generated by Django 5.1.5 on 2026-03-27 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('cash_usd', 'Efectivo USD'), ('cash_eur', 'Efectivo EUR'), ('cup', 'CUP'), ('paypal', 'PayPal'), ('sepa_eur', 'Transferencia SEPA Europa'), ('transfer', 'Transferencia bancaria'), ('crypto', 'Criptomonedas'), ('other', 'Otros')], db_index=True, max_length=20),
        ),
    ]
