# Generated by Django 5.1.5 on 2026-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash_usd', 'Efectivo USD'), ('cash_eur', 'Efectivo EUR'), ('cup', 'CUP'), ('paypal', 'PayPal'), ('sepa_eur', 'Transferencia SEPA Europa'), ('transfer', 'Transferencia bancaria'), ('crypto', 'Criptomonedas'), ('other', 'Otros')], default='cash_usd', max_length=20),
        ),
    ]
