from django.urls import path

from apps.core.views import (
    BrandingSettingsView,
    DashboardView,
    NodeBulkDeleteFilteredView,
    NodeBulkDeleteView,
    NodeCreateView,
    NodeImportView,
    NodeSettingsView,
    NodeUpdateView,
    OpenClawSettingsView,
    ResetPlatformView,
    ReportsSettingsView,
    ServicePlanCreateView,
    ServicePlanSettingsView,
    ServicePlanUpdateView,
    SetupWizardView,
    SettingsHomeView,
    UserCreateView,
    UserManagementView,
    UserUpdateView,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("setup/", SetupWizardView.as_view(), name="setup-wizard"),
    path("setup/<slug:step>/", SetupWizardView.as_view(), name="setup-wizard-step"),
    path("settings/", SettingsHomeView.as_view(), name="settings-home"),
    path("settings/branding/", BrandingSettingsView.as_view(), name="settings-branding"),
    path("settings/users/", UserManagementView.as_view(), name="settings-users"),
    path("settings/users/new/", UserCreateView.as_view(), name="settings-user-create"),
    path("settings/users/<int:pk>/edit/", UserUpdateView.as_view(), name="settings-user-update"),
    path("settings/nodes/", NodeSettingsView.as_view(), name="settings-nodes"),
    path("settings/nodes/import/", NodeImportView.as_view(), name="settings-node-import"),
    path("settings/nodes/bulk-delete/", NodeBulkDeleteView.as_view(), name="settings-node-bulk-delete"),
    path("settings/nodes/bulk-delete-filtered/", NodeBulkDeleteFilteredView.as_view(), name="settings-node-bulk-delete-filtered"),
    path("settings/nodes/new/", NodeCreateView.as_view(), name="settings-node-create"),
    path("settings/nodes/<int:pk>/edit/", NodeUpdateView.as_view(), name="settings-node-update"),
    path("settings/plans/", ServicePlanSettingsView.as_view(), name="settings-service-plans"),
    path("settings/plans/new/", ServicePlanCreateView.as_view(), name="settings-service-plan-create"),
    path("settings/plans/<int:pk>/edit/", ServicePlanUpdateView.as_view(), name="settings-service-plan-update"),
    path("settings/reports/", ReportsSettingsView.as_view(), name="settings-reports"),
    path("settings/openclaw/", OpenClawSettingsView.as_view(), name="settings-openclaw"),
    path("settings/reset/", ResetPlatformView.as_view(), name="settings-reset"),
]
